services:

  incident-service:

    build: .

    ports:
      - "8002:8002"

    
    networks:
      - incident-net


  investigation-worker:

    build: .

    command: >
      python -u -m workers.investigation_worker

    networks:
      - incident-net
  
  analysis-worker:
    build: .

    command: >
      python -u -m workers.analysis_worker

    networks:
      - incident-net
    
    env_file:
      - .env

  dashboard-api:
    build: ./dashboard-api
    ports:
      - "8003:8003"
    networks:
      - incident-net
  


  dashboard-ui:
    build: ./dashboard-ui
    ports:
      - "8080:80"
    networks:
      - incident-net
    env_file:
      - ./dashboard-ui/.env

networks:
  incident-net:
    external: true