services:

  incident-service:

    build: .

    ports:
      - "8002:8002"

    
    networks:
      - incident-net


  investigation-worker:

    build: .

    command: >
      python -u -m workers.investigation_worker

    networks:
      - incident-net
  
  analysis-worker:
    build: .

    command: >
      python -u -m workers.analysis_worker

    networks:
      - incident-net
    
    environment:
      - GROK_API_KEY=${GROK_API_KEY}

networks:
  incident-net:
    external: true