
services:

  api-service:
    labels:
     service: api-service
    build: ./api-service
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  payment-service:
    labels:
     service: payment-service
    build: ./payment-service
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: incidentlab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - incident-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - incident-net


  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - incident-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml


  alertmanager:
    image: prom/alertmanager:latest

    container_name: alertmanager

    ports:
      - "9093:9093"

    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

    networks:
      - incident-net

volumes:
  postgres_data:

networks:
  incident-net:
    external: true